create table Person(id int,name varchar(20),password varchar(20),email varchar(20),gender varchar(20),city varchar(20),country varchar(20))
insert into Person values(1,'Akash','pass','gautama','Male','Nagpur','India')
insert into Person values(1,'Sooraj','pass','sooraj','Male','Nagpur','India')
insert into Person values(3,'Kartik','pass','kartike','Male','Nagpur','India')
insert into Person values(4,'Akshay','pass','akshay','Male','Nagpur','India')
insert into Person values(5,'Harish','pass','harish','Male','Nagpur','India')
insert into Person values(6,'Devanshu','pass','devanshu','Male','Nagpur','India')
insert into Person values(7,'Lucky','pass','lucky','Male','Nagpur','India')
insert into Person values(8,'David','pass','david','Male','Nagpur','India')
insert into Person values(9,'Chetan','pass','chetan','Male','Nagpur','India')
insert into Person values(10,'Harish','pass','harish','Male','Nagpur','India')
select* from Person
